language: node_js
env:
  global:
    # gh-pagesへのdeploy向け
    - GH_USER_EMAIL="azuciao@gmail.com"
    - GH_USER_NAME="azu"
jobs:
  include:
    # deploy
    - stage: deploy
      node_js: '12'
      if: branch = master AND type != pull_request
      before_install:
        # https://calibre-ebook.com/download_linux
        # Install Calibre 3.33.1 that is hard coded in the shell script
        - cat .travis/calibre-3-installer.sh | sudo sh /dev/stdin
        - sudo ln -s /opt/calibre/ebook-convert /usr/local/bin/
        # version check
        - ebook-convert --version
        # https://ipafont.ipa.go.jp/node26
        - mkdir -p ~/.fonts
        - cp ./resources/fonts/ipaexm00301/ipaexm.ttf ~/.fonts/ipaexm.ttf
        - fc-cache -fv
      before_script:
        - |

          $(npm bin)/set-up-ssh --key "$encrypted_55887fb399d9_key" \
                                --iv "$encrypted_55887fb399d9_iv" \
                                --path-encrypted-key ".travis/github_deploy_key.enc"
      script:
        - |
          npm run install:gitbook
          $(npm bin)/update-branch --commands "npm run build:all" \
                             --commit-message "Deploy GitBook build [skip ci]" \
                             --directory "_book" \
                             --distribution-branch "gh-pages" \
                             --source-branch "master"
