version: "3"
services:
  ubuntu-texlive-ja:
    image: korosuke613/ubuntu-texlive-ja-devcontainer
    build: .
    command: sleep infinity
    volumes:
      - ../:/workdir
      - ~/.gitconfig:/root/.gitconfig
      - ./.latexmkrc:/root/.latexmkrc
    environment:
      SHELL: "/bin/bash"